const namePattern = /^[a-zA-Z0-9/_-]+$/;

const normalizeName = (value) =>
  String(value)
    .trim()
    .replace(/\\/g, "/")
    .replace(/^\/+|\/+$/g, "");

const toKebabCase = (value) =>
  normalizeName(value)
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();

const toPascalCase = (value) =>
  toKebabCase(value)
    .split("/")
    .map((segment) =>
      segment
        .split("-")
        .filter(Boolean)
        .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
        .join(""),
    )
    .join("");

const toCamelCase = (value) => {
  const pascalCase = toPascalCase(value);

  return `${pascalCase.charAt(0).toLowerCase()}${pascalCase.slice(1)}`;
};

const validateName = (value) => {
  const name = normalizeName(value);

  if (!name) {
    return "Name is required.";
  }

  if (!namePattern.test(name)) {
    return "Use letters, numbers, slash, underscore, or dash only.";
  }

  return true;
};

const pageTemplate = `<script setup lang="ts">
import { reactive } from "vue";

interface PageProps {
  title?: string;
}

// biome-ignore lint/correctness/noUnusedVariables: 中文：Vue 模板会引用该变量。English: Referenced by the Vue template.
const { title = "{{pascalCase name}}" } = defineProps<PageProps>();

interface PageState {
  ready: boolean;
  version: string;
}

// biome-ignore lint/correctness/noUnusedVariables: 中文：Vue 模板会引用该变量。English: Referenced by the Vue template.
const state = reactive<PageState>({
  ready: true,
  version: "Vue 3.5+ / TS 6.0",
});
</script>

<template>
  <main class="min-h-screen bg-slate-100 px-6 py-10 text-slate-950 dark:bg-slate-950 dark:text-white">
    <section class="mx-auto max-w-5xl border border-slate-200 bg-white/80 p-8 shadow-xl shadow-slate-300/30 dark:border-white/10 dark:bg-white/8 dark:shadow-black/30">
      <p class="text-sm font-bold uppercase text-cyan-700 dark:text-cyan-200">\\{{ state.version }}</p>
      <h1 class="mt-4 text-4xl font-black">\\{{ title }}</h1>
      <p class="mt-4 text-slate-600 dark:text-slate-300">
        Generated by Vue-Launchpad Plop. Replace this page with your feature implementation.
      </p>
    </section>
  </main>
</template>
`;

const componentTemplate = `<script setup lang="ts">
interface {{pascalCase name}}Props {
  description?: string;
  title?: string;
}

// biome-ignore lint/correctness/noUnusedVariables: 中文：Vue 模板会引用该变量。English: Referenced by the Vue template.
const { description = "Reusable Vue-Launchpad component", title = "{{pascalCase name}}" } =
  defineProps<{{pascalCase name}}Props>();
</script>

<template>
  <section class="border border-slate-200 bg-white/80 p-5 shadow-lg shadow-slate-200/40 dark:border-white/10 dark:bg-white/8 dark:shadow-black/30">
    <p class="text-xs font-bold uppercase text-cyan-700 dark:text-cyan-200">
      {{pascalCase name}}
    </p>
    <h2 class="mt-3 text-2xl font-black text-slate-950 dark:text-white">\\{{ title }}</h2>
    <p class="mt-3 leading-7 text-slate-600 dark:text-slate-300">\\{{ description }}</p>
  </section>
</template>
`;

const storeTemplate = `import { defineStore } from "pinia";
import { computed, ref } from "vue";

export interface {{pascalCase name}}State {
  id: string;
  name: string;
}

export const use{{pascalCase name}}Store = defineStore("{{kebabCase name}}", () => {
  const items = ref<{{pascalCase name}}State[]>([]);
  const loading = ref(false);
  const total = computed(() => items.value.length);

  function setItems(nextItems: {{pascalCase name}}State[]) {
    items.value = nextItems;
  }

  function reset() {
    items.value = [];
    loading.value = false;
  }

  return {
    items,
    loading,
    reset,
    setItems,
    total,
  };
});
`;

const apiTemplate = `import { request } from "#app/utils/request.ts";

export interface {{pascalCase name}}Item {
  id: string;
  name: string;
}

export interface {{pascalCase name}}Query {
  keyword?: string;
  page?: number;
  pageSize?: number;
}

export interface {{pascalCase name}}ListResult {
  items: {{pascalCase name}}Item[];
  total: number;
}

export function fetch{{pascalCase name}}List(params?: {{pascalCase name}}Query) {
  return request.get<{{pascalCase name}}ListResult>("/{{kebabCase name}}", {
    params,
  });
}

export function fetch{{pascalCase name}}Detail(id: string) {
  return request.get<{{pascalCase name}}Item>(\`/{{kebabCase name}}/\${id}\`);
}
`;

function createNamePrompt(message) {
  return [
    {
      name: "name",
      type: "input",
      message,
      validate: validateName,
    },
  ];
}

export default function setupPlop(plop) {
  plop.setHelper("camelCase", toCamelCase);
  plop.setHelper("kebabCase", toKebabCase);
  plop.setHelper("pascalCase", toPascalCase);

  plop.setGenerator("page", {
    description: "Generate a typed file-route page under src/pages",
    prompts: createNamePrompt("请输入页面名称 (page name):"),
    actions: [
      {
        type: "add",
        path: "src/pages/{{kebabCase name}}.vue",
        skipIfExists: true,
        template: pageTemplate,
      },
    ],
  });

  plop.setGenerator("component", {
    description: "Generate a reusable Vue component under src/components",
    prompts: createNamePrompt("请输入组件名称 (component name):"),
    actions: [
      {
        type: "add",
        path: "src/components/{{pascalCase name}}.vue",
        skipIfExists: true,
        template: componentTemplate,
      },
    ],
  });

  plop.setGenerator("store", {
    description: "Generate a Pinia setup store under src/store",
    prompts: createNamePrompt("请输入 Store 名称 (store name):"),
    actions: [
      {
        type: "add",
        path: "src/store/{{kebabCase name}}.ts",
        skipIfExists: true,
        template: storeTemplate,
      },
    ],
  });

  plop.setGenerator("api", {
    description: "Generate a typed request module under src/api",
    prompts: createNamePrompt("请输入 API 模块名称 (api module name):"),
    actions: [
      {
        type: "add",
        path: "src/api/{{kebabCase name}}.ts",
        skipIfExists: true,
        template: apiTemplate,
      },
    ],
  });
}
