<script setup lang="ts">
import { reactive } from "vue";

interface PageProps {
  title?: string;
}

// biome-ignore lint/correctness/noUnusedVariables: 中文：Vue 模板会引用该变量。English: Referenced by the Vue template.
const { title = "List" } = defineProps<PageProps>();

interface PageState {
  ready: boolean;
  version: string;
}

// biome-ignore lint/correctness/noUnusedVariables: 中文：Vue 模板会引用该变量。English: Referenced by the Vue template.
const state = reactive<PageState>({
  ready: true,
  version: "Vue 3.5+ / TS 6.0",
});
</script>

<template>
  <main class="min-h-screen bg-slate-100 px-6 py-10 text-slate-950 dark:bg-slate-950 dark:text-white">
    <section class="mx-auto max-w-5xl border border-slate-200 bg-white/80 p-8 shadow-xl shadow-slate-300/30 dark:border-white/10 dark:bg-white/8 dark:shadow-black/30">
      <p class="text-sm font-bold uppercase text-cyan-700 dark:text-cyan-200">
        {{ state.version }}
      </p>
      <h1 class="mt-4 text-4xl font-black">{{ title }}</h1>
      <p class="mt-4 text-slate-600 dark:text-slate-300">
        Generated by Vue-Launchpad Plop. Replace this page with your feature implementation.
      </p>
    </section>
  </main>
</template>
